-- Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;

-- List the number of films per category.
SELECT 
	ca.name as category_name, 
    count(fc.film_id) as film_count
FROM 
	film_category fc
JOIN 
	category ca USING (category_ID)
GROUP BY 
	ca.name
ORDER BY 
	film_count DESC;

-- Retrieve the store ID, city, and country for each store.
SELECT 
	s.store_id,
    c.city,
    cr.country
FROM
	store s
LEFT JOIN 
	address a USING (address_id)
LEFT JOIN
	city c ON a.city_id = c.city_id
LEFT JOIN
	country cr ON c.country_id = cr.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT 
	s.store_id,
	sum(p.amount) as revenue
FROM
	payment p
LEFT JOIN 
	staff s ON p.staff_id = s.staff_id
GROUP BY s.store_id;
	

-- Determine the average running time of films for each category.
SELECT 
	ca.name as category_name, 
    floor(AVG(f.length)) as avg_film_length_rounded_down
FROM 
	film_category fc
LEFT JOIN 
	category ca USING (category_ID)
LEFT JOIN
	film f ON fc.film_id = f.film_id
GROUP BY 
	ca.name
ORDER BY 
	AVG(f.length) DESC;





